export const actionTypes = {
    UPDATE_HOVER_TILE: 'UPDATE_HOVER_TILE',
    UPDATE_HOVERED_AGENT_NAME: 'UPDATE_HOVERED_AGENT_NAME',
    UPDATE_HOVERED_AGENT_LAST_EXECUTION_CHAIN: 'UPDATE_HOVERED_AGENT_LAST_EXECUTION_CHAIN',
    UPDATE_HOVERED_RESOURCE_NAME: 'UPDATE_HOVERED_RESOURCE_NAME',
    UPDATE_HOVERED_ITEM_NAME: 'UPDATE_HOVERED_ITEM_NAME',
};