export const actionTypes = {
    UPDATE_HOVER_TILE: 'UPDATE_HOVER_TILE',
    UPDATE_HOVERED_AGENT: 'UPDATE_HOVERED_AGENT',
    UPDATE_HOVERED_AGENT_LAST_EXECUTION_CHAIN: 'UPDATE_HOVERED_AGENT_LAST_EXECUTION_CHAIN',
    UPDATE_HOVERED_RESOURCE: 'UPDATE_HOVERED_RESOURCE',
    UPDATE_HOVERED_ITEM: 'UPDATE_HOVERED_ITEM',
    UPDATE_HOVERED_BUILDING: 'UPDATE_HOVERED_BUILDING',
    UPDATE_CLOCK_TIME: 'UPDATE_CLOCK_TIME',
};